/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "GPIO/stm32f103x6_GPIO.h"

/*Functions declarations*/
void clock_init();
void GPIO_init();

int main()
{
   volatile int i;
   clock_init();
   GPIO_init();

   while (1)
   {

      /*If the button at PA1 is pressed*/
      if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1) == GPIO_PIN_LOW)
      {
        MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN1);      /*Toggle the LED*/

        /*A loop for the button to be a signle press*/
        while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1) == GPIO_PIN_LOW);
      }

      /*If the button at PA13 is pressed*/
      if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN13) == GPIO_PIN_HIGH)
      {
        MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN13);      /*Toggle the LED*/
      }

      /*Simple delay*/
      for(i = 0;  i < 10000; i++);
   }

   return 0;
}


void clock_init()
{
   /*Enable GPIO_A*/
   APB2_PERI_CLOCK_EN(APB2_IOPA);

   /*Enable GPIO_B*/
   APB2_PERI_CLOCK_EN(APB2_IOPB);
}


void GPIO_init()
{
  GPIO_Pin_Config_t config;
  
  /*PA_13 as floating input*/
  config.pinNumber = GPIO_PIN13;
  config.pinMode = GPIO_MODE_INPUT_FLOATING;
  MCAL_GPIO_Init(GPIOA, &config);

  /*PA_1 as floating input*/
  config.pinNumber = GPIO_PIN1;
  config.pinMode = GPIO_MODE_INPUT_FLOATING;
  MCAL_GPIO_Init(GPIOA, &config);

  /*PB1 as output push-pull 10MHZ*/
  config.pinNumber = GPIO_PIN1;
  config.pinMode = GPIO_MODE_GP_OUTPUT_PP_10MHZ;
  MCAL_GPIO_Init(GPIOB, &config);

  /*PB13 as output push-pull 10MHZ*/
  config.pinNumber = GPIO_PIN13;
  config.pinMode = GPIO_MODE_GP_OUTPUT_PP_10MHZ;
  MCAL_GPIO_Init(GPIOB, &config);
}
