/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>

#define RCC_BASE  	0x40021000
#define PortA_BASE  0x40010800
#define APB2EN_R  	*(volatile unsigned long *)(RCC_BASE + 0x18)
#define CRH_R  		*(volatile unsigned long *)(PortA_BASE + 0x04)
#define GPIO_ODR_R  *(volatile unsigned long *)(PortA_BASE + 0x0c)

#define IOPAEN 	(1 << 2)
#define PA_13	(1 << 13)

typedef union{
	volatile uint32_t all_bits;
	struct{
		volatile uint32_t reserved : 13;
		volatile uint32_t P_13: 1;
	}Pin;
}Uregister_t;

volatile Uregister_t *ODR_R = (volatile Uregister_t *)(PortA_BASE + 0x0c);

int main(void)
{
	APB2EN_R |= IOPAEN;
	CRH_R = (CRH_R & 0xFF0FFFFF) + 0x00200000;

	while(1)
	{
		ODR_R->Pin.P_13 = 1;
		for(int i = 0; i < 500000; i++);
		ODR_R->Pin.P_13 = 0;
		for(int i = 0; i < 500000; i++);
	}
}
